import { serie } from './serie.js';
export const data = [
    new serie(1, "Breaking Bad", "AMC", 5, "Set and filmed in Albuquerque, New Mexico, the series tells the story of Walter White, a struggling and depressed high school chemistry teacher who is diagnosed with lung cancer", "https://www.amc.com/shows/breaking-bad", "https://rukminim2.flixcart.com/image/850/1000/xif0q/poster/4/f/f/small-spos7595-poster-tv-show-breaking-bad-walter-white-bryan-original-imaghnjz8xrq3hze.jpeg?q=90&crop=false"),
    new serie(2, "Orange Is the New Black", "Netflix", 6, "The series begins revolving around Piper Chapman, a woman in her thirties living in New York City who is sentenced to 15 months in Litchfield Penitentiary", "https://www.netflix.com/co/title/70242311", "https://ntvb.tmsimg.com/assets/p13812572_b_h10_aa.jpg?w=960&h=540"),
    new serie(3, "Game of Thrones", "HBO", 7, "American fantasy drama", "https://www.hbo.com/game-of-thrones", "https://www.officialtheatre.com/wp-content/uploads/2021/04/game-of-thrones-banner.jpg"),
    new serie(4, "The Big Bang Theory", "CBS", 12, "Leonard and Sheldon are brilliant physicists—geniuses in the laboratory but socially challenged everywhere else. Enter beautiful, street-smart neighbor Penny, who aims to teach them a thing or two about life. Despite their on-again, off-again relationship in the past, Leonard and Penny have finally gotten married. Even Sheldon has found a female companion, entering into a relationship agreement with neurobiologist Amy Farrah Fowler, and he recently took their relationship to the next level by marrying her after a long courtship. In their free time, Leonard and Sheldon enjoy fantasy role-playing games with their ever-expanding universe of friends, including fellow scientists Koothrappali, Wolowitz, and Wolowitz’s adorable microbiologist wife, Bernadette, who is adjusting to life with their two children.", "https://www.cbs.com/shows/big_bang_theory/about/", "https://storage.googleapis.com/cdn.spoilertv.com/images/headers/the-big-bang-theory.jpg"),
    new serie(5, "Sherlock", "BBC", 4, "Sherlock depicts consulting detective Sherlock Holmes (Benedict Cumberbatch) solving various mysteries in modern-day London. Holmes is assisted by his flatmate and friend, Dr John Watson (Martin Freeman), who has returned from military service in Afghanistan with the Royal Army Medical Corps", "https://www.bbc.co.uk/programmes/b018ttws", "https://mir-s3-cdn-cf.behance.net/project_modules/1400/e6fd3532032273.566b40caa5ef7.jpg"),
    new serie(6, "A Very English Scandal", "BBC", 2, "A Very English Scandal is a fact-based three-part British television comedy-drama miniseries based on John Preston's book of the same name.", "https://www.bbc.co.uk/programmes/p065smy4", "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/465ed40e-5213-4017-a8db-febd2b45c191/0207cbfe-b11a-4693-af0d-59b5bf509787?host=wbd-images.prod-vod.h264.io&partner=beamcom"),
];
